### ISSUE TITLE
Incompatible functions

### ISSUE THREAD

**Issue by monacofj** [courselab/hello-world-GabrielPattiSC#2]
A função `system(PAUSE)`  que você utilizou é específica de Windows.
Isso quer dizer que seu programa não vai compilar corretamente em Linux ou MacOS.

Esse "truque" da `system(PAUSE)`  é utilizado para impedir que a janela do prompt se feche quando você executa diretamente clicando sobre o ícone do program no Wildws. Uma alternativa é executar o programa diretamente a partir de uma IDE como o CodeBlocks. Outra alternativa é abrir o prompt do Windows (prompt de comandos) e digitar o nome do programa diretamente na linha de comando.

E o truque não é necessário em outras plataformas como MacOS e Linux.

Por hora não é um problema, mas adiante pode ser que seja.
Ensinarei um outro truque que funciona no Windows, Linux e MacOS.

**Comment by GabrielPattiSC** [comment]
Entendi professor, Obrigado pelo feedback!
Realmente eu usei esse tuque por que a janela do prompt tava fechando.
Então eu posso fazer os próximos pela prompt de comando do próprio windows? ela substituiría o git bash?

**Comment by monacofj** [comment]
Sim!
